name: Backup

on:
  # schedule:
  #   - cron: "0 12 * * *"
  workflow_dispatch: {}

jobs:
  matrix:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        run: echo 'matrix=[{"owner":"USA-RedDragon"},{"owner":"AstroGardenLLC"},{"owner":"kubewg-net"},{"owner":"USA-RedDragon-ORG"}]' >>"$GITHUB_OUTPUT"

  authenticate-authentik:
    uses: ./.github/workflows/authentik.yaml
    permissions:
      id-token: write
    with:
      authentik-url: ${{ vars.AUTHENTIK_URL }}
    secrets:
      client-id: ${{ secrets.AUTHENTIK_CLIENT_ID }}

  backup:
    name: Backup
    needs: [matrix, authenticate-authentik]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        owners: ${{fromJson(needs.matrix.outputs.matrix)}}
    permissions:
      id-token: write
    steps:
      - name: Authentik to Minio OIDC
        run: |
          echo no-op
          echo ${{ needs.authenticate-authentik.outputs.token }}
      - name: GitHub Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          owner: ${{ matrix.owners.owner }}
      - name: Backup repos
        id: backup
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          set -eu
          gh auth setup-git
          func do_backup() (
            set -eu
            source <(yq -p=json -o=shell <<<"$1")
            mkdir -p "${{ matrix.owners.owner }}"
            reponame="${{ matrix.owners.owner }}_$name"
            repodir="${{ matrix.owners.owner }}/$name"
            git clone --mirror "https://github.com/${{ matrix.owners.owner }}/$name" "$reponame"
            tar --sort=name --mtime="$pushedAt" -cf "$reponame.tar" "$reponame"
            rm -rf "$reponame"
            mkdir -p "$repodir"
            mv "$reponame.tar" "$repodir"
            du -sh "$repodir"
            aws --endpoint-url "${{ vars.MINIO_ENDPOINT }}" s3 sync "$repodir" "s3://${{ vars.MINIO_BUCKET }}/$repodir"
            rm -rf "$repodir"
          )
          export -f do_backup
          gh repo list --no-archived --limit=9999 --json name,pushedAt ${{ matrix.owners.owner }} \
            | jq -c 'sort_by(.name | ascii_downcase) | .[]' \
            | parallel do_backup 2>&1 \
            | ts $'%H:%M:%S' \
            | tee log.txt
